runtime: python312
service: app-medicos
service_account: id-apps-convenmed-bucket@gnp-admonproveedoressalud-qa.iam.gserviceaccount.com
handlers:
  - url: /(.*\.(css|gif|png|jpg|js|woff2|json))$
    static_files: build/web/\1
    upload: build/web/.*\.(css|gif|png|jpg|js|woff2|json)$
  - url: /assets/(.*)
    static_files: build/web/assets/\1
    upload: build/web/assets/.*
  - url: /canvaskit/(.*)
    static_files: build/web/canvaskit/\1
    upload: build/web/canvaskit/.*
  - url: /icons/(.*)
    static_files: build/web/icons/\1
    upload: build/web/icons/.*
  - url: /(.*)
    static_files: build/web/index.html
    upload: build/web/index.html
